#Author: Ema Alsina, M.Sc.
#e.m.alsina-2@umcutrecht.nl
#University Medical Center Utrecht
#29/6/2022

# this function identifies the trimester when COVID diagnosis occurred. 
#inputs: 
  #pregnancy dataset with minimum person_id and trimester dates (generated by trimester function)
  # cov_date: dataset with person_id and date of diagnosis (labeled cov_date)


cov_trimester<-function(preg_data=my_PREG, cov_data=cov_data){

#compare my_PREG for each covid diagnosis per person per pregnancy
  # 1) match person_ids
  # 2) my_PREG long to wide by preg_ID, select trim variables
  # 3) cov_data long to wide by date
  # 4) for each row check each covid date (in case of multiple diagnoses) to each pregnancy dates (in case of multiple pregnancies)
 
cov_PREG_long<- preg_data[preg_data$person_id%in%cov_data$person_id,] 
cov_PREG_long<-cov_PREG_long[order(cov_PREG_long$person_id),]

cov_PREG<-dcast(setDT(cov_PREG_long), person_id ~ rowid(person_id), value.var = ("pregnancy_id"))
cov_PREG<-cov_PREG[order(cov_PREG$person_id),]

preg_names<-vector()
for(i in 2:ncol(cov_PREG)){
  preg_names[i-1]<-paste0("pregnancy_",(i-1))
}

colnames(cov_PREG)<-c("person_id",preg_names)


cov_data<-cov_data[cov_data$person_id%in%cov_PREG$person_id,]
max_cov<-max(table(cov_data$person_id))
cov_data<-dcast(setDT(cov_data), person_id ~ rowid(person_id), value.var = ("cov_date"))
cov_data<-cov_data[order(cov_data$person_id),]

id_freq<-(table(cov_PREG_long$person_id))

cov_dates<-cov_data[,2:(ncol(cov_data))]

my_name<-vector()
for(i in 1:max_cov){
my_name[i]<-paste0("cov_diag_", i)
}

# cov_diag_long<-df <- data.frame(matrix(ncol = max_cov, nrow = 0))
# colnames(cov_diag_long)<-my_name
# 
# for(i in 1:max_cov){
#   my_dates<-cov_dates[,..i]
#   print(my_dates)
# cov_diag_long[,i]<-rep.int(x = my_dates, times=id_freq)
# }
# 
# rep.int(as.numeric(cov_dates[,1]),1:10)
# rep.int(c(5,4,3),(1:3))

if((all(cov_data$person_id==cov_PREG$person_id))==F){print("person_id match failure");break}else{print("id match OK")}

cov_vars<-vector()

for (i in 2:ncol(cov_data)){
  diag_name<-paste0("cov_date_",(i-1))
  colnames_preg<-c(colnames(cov_PREG), diag_name)
  cov_PREG<-cbind(cov_PREG, cov_data[,..i])
  colnames(cov_PREG)<-colnames_preg
  cov_vars[i-1]<-diag_name
}

# now I have the covid dates matched to the right person_id and per pregnancy in wide format by PREG_ID- 
# now I need it back to long to cbind to my_PREG to calculate the trimester (if any) in which diagnosis occurred
# problem: variable column number and column names

interim_cov_PREG<-melt.data.table(cov_PREG, id.vars = c("person_id", cov_vars),
     measure.vars = c(preg_names),variable.name = "preg_num", value.name = "pregnancy_id", na.rm = T)

order_cov_PREG<-interim_cov_PREG[order(interim_cov_PREG$person_id),]

if((all(order_cov_PREG$person_id==cov_PREG_long$person_id))==F){print("person_id match failure");break}else{print("id match OK")}

#now combine the formated covid dates with 
final_cov_dates<-order_cov_PREG %>% select(any_of(cov_vars))

final_cov_PREG<-cbind(cov_PREG_long, final_cov_dates)


final_cov_PREG$cov_trimester<-0

for(i in 1:length(cov_vars)){

final_cov_PREG$cov_trimester[cov_date$cov_date<=final_cov_PREG$trim_1_start]<-NA
final_cov_PREG$cov_trimester[(cov_date$cov_date>=final_cov_PREG$trim_1_start)&  (cov_date$cov_date<= final_cov_PREG$trim_1_end)]<-1
final_cov_PREG$cov_trimester[(cov_date$cov_date>=final_cov_PREG$trim_2_start)&  (cov_date$cov_date<= final_cov_PREG$trim_2_end)]<-2
final_cov_PREG$cov_trimester[(cov_date$cov_date>=final_cov_PREG$trim_3_start)&  (cov_date$cov_date<= final_cov_PREG$trim_3_end)]<-3
final_cov_PREG$cov_trimester[cov_date$cov_date>=final_cov_PREG$trim_3_end]<-NA
}
return(final_cov_PREG)}

